### ISSUE TITLE
DATA:Database Connection

### ISSUE THREAD

**Issue by JamshidMajidov** [YoungCentreDotnet/Apteka#3]

**Comment by pragramist-07** [comment]
![image](https://github.com/YoungCentreDotnet/Apteka/assets/122969603/831626d2-0bad-4530-a07e-7e90064e6794)

**Comment by Dadaxon-07** [comment]
![image](https://github.com/YoungCentreDotnet/Apteka/assets/122969603/8226a521-0a4a-4716-a138-8ee472388397)

**Comment by AslanbekHasanov** [comment]
Closes #4
